== Preface

[verse]
____
"`How blest is the child of the Lord,
When taught by his Father to run,
When led by the light of His Word,
And cheered by the beams of His Sun.`"
____

The truth of this was exhibited, in a remarkable degree, by the child of the Lord,
a memoir of whose state and daily walk is now
presented in extracts from her private journal.
Those, whose privilege it is to read the following pages,
will see how early and clearly she was taught, by her heavenly Father,
to run in the way of His commandments; how implicitly she followed the light of His Word,
which led her out of darkness into His marvellous light,
and into the glorious liberty of the children of God.
And, further, it will be seen,
how she was cheered by the glorious beams of His sun when walking
through the "`valley of the shadow of death;`" she could,
in truth, say, that she feared no evil, for that her Lord, her hope of salvation,
was with her, and that He gave her the victory over death, hell, and the grave.

Those who read this preface, would do well to peruse, with deep attention,
the extracts from the journal, and, as they read,
to seek to have their minds brought into subjection to the same spirit which led,
and guided, and ruled this young and devoted Christian, who,
through the grace given to her, could adopt the language, "`I have fought a good fight;
I have finished my course; I have kept the faith;
henceforth there is laid up for me a crown of righteousness, which the Lord,
the righteous Judge, will give me at that day, and not to me only,
but also unto all those that love His appearing.`"
Then will they, with her, also experience, that the work of righteousness shall be peace,
and the effect thereof, quietness and assurance forever.^
footnote:[Written by a valued friend who was intimately acquainted with,
but not related to, Mary Ann Gilpin.]
