== Extracts from Her Letters

[.letter-heading]
To a Friend.

[.signed-section-context-open]
Durdham Down, 4th 6mo. 1830.

May I encourage thee to trust to Israel`'s Shepherd for support,
and to look to Him in every trial!
I have richly experienced His mercy, having long been, at times, a sufferer,
and I believe that thou too hast done so.
O then, my dear E+++______+++, fear not! thou art, I feel assured, gently dealt with,
for though, with unmerited kindness, our heavenly Father extends His hand to wound,
never could we, I think, find it slow to heal.
Mayest thou find, in thy present precarious state,
that in thy weakness the Lord is thy strength,
and thou wilt then be able to go on thy way with gratitude and joy.
Thy heart, I humbly trust, is fixed on the Rock which cannot be moved; and,
my dear friend, I do sincerely desire, that it may continue fixed on it to the end.
Travellers to the heavenly Canaan must expect to meet with trials on their journey;
but oh how unspeakably precious is the support granted them by their heavenly Guide, if,
with sincerity they can apply to Him for it!
My own health is still very delicate, and the future feels peculiarly uncertain.
I do, however, endeavour to trust, that,
whether the result of these continued attacks be life or death,
I may be resigned to the divine will--that will can
alone be good--and oh that it may become ours.

Farewell, my dear E+++______+++. Though we may never be permitted to meet again on earth, I do,
at times, venture humbly to anticipate, a meeting in a better and happier world.
And my most earnest desires for thee are, that as thy day approaches its close,
thy sun may become brighter and brighter, and that, as thy bodily strength fails thee,
God may, indeed, prove "`the strength of thy heart and thy portion forever!`"

[.letter-heading]
To Her Father.

[.signed-section-context-open]
Bristol, 18th 8mo. 1830.

And now, my beloved father, thou wilt be anxious to know how I am, and it will, I know,
give thee pleasure to find that I don`'t consider
myself at all worse than when thou left home,
though I certainly do not gain much, if any strength;
and daily am I reminded that my long continuance here is very uncertain, so much so,
that I feel, at present,
unable to look forward even to what we generally call a very short time.
I long that while strength is permitted me, my work may be accomplished,
that I may be made ready for the saints`' inheritance, and that all my dear friends,
but especially that my much loved family, may be made willing to resign me,
should I be early called to my "`heavenly Father`'s house.`"
I have of late, more than I have ever before done,
been led to contemplate the close of life, and through the mercy of that Guide,
who has hitherto been pleased to lead my wandering footsteps,
it is not accompanied by feelings of dread.
No! my dear father, I have so often found help extended in the needful time,
that I do believe, humbly believe,
that strength sufficient for my day will still be granted me.
How indescribably precious is it to know "`in whom we have believed,`" to
feel that we have a safe refuge from every storm in the "`Rock of Ages.`"

Thou, my beloved parent, hast had trials, but perhaps greater ones may yet await thee;
yet trials are no doubt wisely intended for our purification; and do they not,
ought they not, to direct our attention to those joys which can alone prove lasting?
Under every trial I trust that thou wilt feel divine support extended;
under every bereavement may my dear father feel
that the hand of love has permitted it for good;
and that the chastising rod has been sent in mercy; then shouldest thou, ere long,
be called to surrender to Him who gave her, one dear object of thy tender affection,
shouldst thou have to witness her strength rapidly decline, and each day convince thee,
more and more, that she is, in the morning of her day, hastening to her grave,
mayest thou, and all my dear relatives,
be supported by that strength which is alone sufficient in times of extremity;
and may you be comforted by the same sweet comfort with
which "`I myself have been comforted of God.`"

May all my beloved friends find Him to be their Guide, their Comforter, their Friend.

[.letter-heading]
To Her Parents.

[.signed-section-context-open]
Birmingham, 1st 8mo. 1831.

After we left you, mingled, indeed, were the feelings of my heart,
severe was the pang it cost me to leave those who are
bound to me by the closest ties of affection;
but I knew that it was not in my own will, or for my own pleasure that I left you,
and this consideration was truly comforting.
Yes, and I could rejoice in the prospect of being engaged, though so very unworthy,
in the service of Him to whom I desire to surrender myself entirely,
and I hope I am willing to give up all things for His sake, remembering with gratitude,
that the trials and sufferings of this present time "`are not
worthy to be compared with the glory that shall be revealed.`"

This ride (from Gloucester to Birmingham) was one which I hope I shall long remember.
A peace which "`passeth all understanding,`" was permitted,
and a saving knowledge of Christ Jesus never appeared more unspeakably precious.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
26th 8mo. 1831.

And now thou wilt, I think,
be anxious to know how I am getting on in the
way in which I believe it is my duty to walk.
Still tenderly and mercifully dealt with,
I feel that I have abundant cause for thankfulness.
Although, at times, much bowed down in spirit,
I can yet rejoicingly trust in an arm of strength--I can yet look unto Jesus,
with confidence, as my Saviour and my God.
What an unspeakable favour to have such a Pilot to our
barks! such a Guide to the haven of eternal rest!
My dear aunt`'s house has proved a very comfortable home,
and her great kindness I must ever sensibly feel; but,
after passing through a season of deep conflict,
I told her that I believed a greater sacrifice was required of me, and that I must,
ere very long, lodge at +++_______+++`'s. When I left home, this was hid from my eyes;
and I cannot but admire the wisdom which has hitherto marked every dispensation of
my merciful Guide concerning me--nothing has yet been revealed,
but what strength has been given to me to perform;
and I trust my beloved parents will be willing to leave me to Him whose dealings
with me have been and are past finding out.--Since writing the above,
I have spoken to +++_______+++, who, on my proposing for a time to become his housekeeper,
said, that nothing would give him more pleasure--he was very much obliged to me.
I cannot tell thee with what feelings I heard him say this.

They are often sorrowful on his account, yet then, and at some other seasons,
I have felt a degree of encouragement about him.

[.letter-heading]
To Her Sister J+++_______+++.

[.signed-section-context-open]
Supposed 1832.

Feeling that my long continuance here is peculiarly uncertain, I do,
my beloved J+++_______+++ wish, as much as possible, for my work to be accomplished.
It is with this wish that I pen these few lines to my much loved and ever dear sister.
When I am gone--"`when this mortal shall have put on immortality`"--may
I entreat thee to endeavour to follow,
faithfully to follow, the guidance of the Lord; obey His still small voice within,
which will assuredly lead thee onwards in the path of life.
Oh my dearest J+++______+++ I cannot express my fervent desires on thy account,
but I must tell thee, that, under the idea of parting from my precious sister,
I am consoled by the prospect of a reunion in heaven.
I shall not I trust be disappointed--no, I believe I shall not--thou wilt, ere long,
I hope, follow me to the land where, through unmerited mercy and condescension,
I have a hope of landing in safety.

To thee, dear J+++______+++ when I have left you, the little ones will be left.
Mayest thou be strengthened to strengthen them,
and lead them on in the path in which I have used my
feeble endeavours to advance their footsteps.
Thou wilt, I trust, my beloved sister,
have a better Guide than I could be--to Him I feel that I can commend thee
and all that are dear to me--all my much beloved family and many friends.
To the Shepherd of the fold I can safely leave you,
believing that His fostering care will be extended towards you.
Dear J+++______+++ we have for some time past, at least I have,
anticipated being much longer together here;
but though I now believe it to be the divine will that it should be otherwise,
our separation will not, I trust, be long.
Thou must think of me; and may I beg thee, as I have so often done,
to set apart some time each day for waiting upon God--thy duties to Him are higher,
and of more importance than any other; thou wouldst find satisfaction in serving Him,
and I do believe, ere very long, thou wilt find peace.
Remind the dear children of what I have told them.
Wilt thou tell them, I hope to meet them all again in a better world?
Farewell my dearly loved sister!
We part, I humbly hope to meet again.
Here trials have been ours;
but in the land whither I trust I am going none can ever assail us.
No, it is a kingdom of perfect purity,
into which the "`ransomed and redeemed of the Lord`" are permitted to enter.

Accept, my beloved sister, my fervent desires for thy happiness,
on the twenty-second anniversary of thy birth; and believe me,
though not often expressed in this way,
thy everlasting welfare is most near and dear to my heart.
Oh linger not my endeared J+++______+++ in the path of life,
but be thou "`steadfast and immovable, always abounding in the work of the Lord!`"
Hesitate not, my precious sister,
to declare thyself on God`'s side! let us not be ashamed to confess Christ before men,
but let us acknowledge Him as our Saviour, our Prince, our Leader,
and our all-sufficient Advocate with the Father!

I cannot but regard the forgiving others of very great importance, for if we forgive not,
from our hearts, our fellow travellers here, how can we expect to have our many,
many backslidings not only forgiven but remembered no more?

Farewell, dearest J+++______+++. That Christ may be more and more thy all in all,
is the heartfelt prayer of thy much attached sister.

[.letter-heading]
To Her Brother Charles.

[.signed-section-context-open]
1832.

Under a renewed and vivid sense of the "`beauty of holiness,`" I do,
my much loved brother, sit down, once more to address thee;
and though I am fully convinced that it is no
new thing that I can say to thee on the subject,
I would again affectionately entreat thee to "`gird up the loins of thy mind, be sober,
and hope to the end.`"
I would again, my dearest Charles, express the very fervent desire of my heart,
that it may be thy privileged experience,
to live very near thy heavenly Guide--"`the Spirit itself bearing
witness with thy spirit`" that thou art a child of God! and let us
consider in what manner the children of God ought to live;
let us contemplate their path; and let us, oh let us,
earnestly strive to walk as they ought to walk--
doing all to the glory of Him who died for us,
and rose again.
Oh dear Charles! let us not halt by the way,
but press forwards towards the prize of our high calling!
Let me earnestly beg thee, not to omit any opportunity for retirement,
and do not suffer such seasons to be shorter, and less frequent,
from not deriving all the benefit thou mayest expect from them--persevere,
and I cannot doubt thy obtaining the blessing;
the promise continues to be fulfilled to the "`willing
and obedient,`" of eating "`the good of the land.`"
My thoughts will follow thee with very tender interest,
and I shall most earnestly desire thy preservation in the path of obedience.
Look continually unto Jesus!
In every time of trial and temptation,
seek counsel from Him who alone is able to save to the uttermost those who come unto Him.
Keep close to thy heavenly Guide,
and He will lead thee in safe paths--He will make hard things easy,
and crooked things straight!
Only yield thy heart to Him, and all will, all must be well!
Farewell, my beloved brother; time will not admit of my adding more than that I am,
with much love, and best desires for thy eternal welfare, thy much attached sister.

[.letter-heading]
To the Same.

Thou asks me for my views respecting your reading meetings.
Oh that thou mayest experience the guidance of a better Counsellor! but,
with the help He is graciously pleased to afford, I will endeavour, if I may,
to comply with thy request.
It may be done, I think, in few words.
The reading of the Scriptures can only be made profitable,
as our understandings are opened by Him, by whose inspiration they were given.
Are your meetings calculated to deepen your dependance on the influences of that Spirit,
which, if obeyed, would lead into all truth; or are you rather induced to endeavour,
with the natural eye, to discern those things which can only be spiritually discerned?
That thou mayest indeed receive fully the Spirit which is of God,
and be permitted thereby to know "`the things which are freely
given us of God,`" that He may preserve thee from all evil,
and lead thee forward in the way everlasting;`" that,
He may strengthen thee in all things to do His will, is, my endeared brother,
the fervent prayer of thy much attached sister.

[.letter-heading]
To the Same.

[.signed-section-context-open]
12th 9mo. 1833.

I am indeed glad to find that thou hast, in thy frequent companion,
one whom thou believes to be really serious.
As thou becomes more acquainted with him,
I trust thou wilt really find him a faithful follower of the Lord Jesus; and oh,
mayest thou, my beloved Charles, be his companion.
I can easily understand his objections to first-day visiting;
and though thou thinks thou mayest pursue a different line of conduct, I trust,
my dear brother, thou wilt never go any where,
where thou canst not spend the day properly.
"`Remember the Sabbath day to keep it holy,`" was one
of the commands under the Mosaic dispensation,
and though the law was only as our school-master to bring us to Christ, still,
my beloved Charles,
our gracious Saviour himself sweetly enjoined on his immediate
followers that they should "`do good`" on this day of outward rest;
and oh that we may be enabled to do all to His glory!

How uncertain, my dear brother, is everything here! and how highly important is it,
therefore, to know an interest in Christ,
that when all terrestrial pleasures shall have passed away forever,
we may have a mansion in that "`house not made with hands, eternal in the heavens.`"
Oh that we may, with more earnestness, endeavour to follow Jesus,
wherever He is pleased to lead us!

[.letter-heading]
To Her Sister S+++______+++.

[.signed-section-context-open]
Clevedon, 8th 5mo. 1834.

I should not myself like,
my beloved S. that thy birthday should pass without this kind of proof of my remembrance,
and therefore I have begun it, already fearing, among my many engagements,
I may be prevented doing so.
And now what shall I say to thee, my beloved girl!
I do indeed long, that, above all things,
thou mayest be found "`walking in the truth;`" that none of the pleasures, which,
in youth`'s bright morning, are often presented to the mind in beautiful colours,
should tempt thee away from the pursuit of that which alone, in years to come,
will prove to have substantial brightness--the "`pearl of great price.`"
My precious girl,
I desire for thee to be possessed of the treasure which "`maketh truly rich!`"
In the retrospect of the past year,
I trust thou wilt be able to see that thou hast made some straight steps; but,
my dear S+++______+++, let me encourage thee more faithfully to follow Him whose voice,
I rejoice in believing, thou hast heard, alluring thee into the green pastures of life,
and inviting thee to partake of living water.
Oh that thou mayest indeed drink thereof, that thy soul may live and not die!
The river of God is full of mater!
Let us rejoice in this knowledge; and oh let it be encouraging to us,
to "`pitch our tents`" by its side!
No pleasure could I have on earth more delightful,
than that of seeing all the members of my beloved family in the way to Zion,
with their faces turned thitherwards!
I shall be very glad to have thee here a little while with me.
We have taken two most beautiful walks--the one last evening
was particularly so--to the ruins of Walton Castle.
On the post of one of the towers is written, in pencil, "`Telle est la vie`";
and on the opposite one, the striking words, "`Eternity!
Eternity!
Eternity!`"
The building is in complete ruins, and is, indeed,
calculated to convey impressions of the great importance of laying up
for ourselves treasure in that world where all is lasting!
I much enjoy the view of the sea; this, too, is a wonderful proof of divine power;
indeed on every hand we may mark the divine finger:

[verse]
____
"`In every leaf that trembles on the breeze
I hear the voice of God among the trees!`"
____

Farewell, my beloved girl!
May the great and good Shepherd carry thee in the arms of His love;
and mayest thou ever experience Him to be a shelter from the storm,
and as the shadow of a great rock in a weary land!
I am, as ever, thy much attached sister.

[.letter-heading]
To Her Brother Charles.

[.signed-section-context-open]
9th 11mo. 1834.

I think I mentioned in my last, my beloved brother, that M. A. M. was gone to Penzance,
to see dear J. B. She stayed with her several days, and on the evening before she left,
told her plainly, that her complaint was considered incurable.
For a few minutes she was much agitated, but soon became calm;
and in a remarkable manner, in a very short time,
seemed fully to realize the hour through which she passed--I think it may be said,
gratefully rejoicing in that Saviour,
the arms of whose everlasting love were so evidently underneath her,
strengthening and protecting her in the "`valley of the shadow of death.`"
Her first emotions on hearing of her critical state, were those of grief,
in the remembrance of her manifold transgressions.
"`Oh I have been a rebellious, a backsliding child!`" she exclaimed,
as her beloved maternal friend was pressing upon her,
the only work which was left for her to do.

During the few remaining hours of her stay with her, she was mostly engaged in prayer.
She sent many impressive messages to her friends,
and put many of her little things for several whom she named.
She took a calm, final farewell of M. A. M. on the 13th of last month,
after which she sunk very rapidly; but as her bodily strength declined,
her inward man evidently fast strengthened; and ere the close of another week,
she sent the following message to her friend--"`Tell her my body is fast sinking,
but I do hope I may say, "`that Christ is my all and that my life is in Him.`"
She conversed freely each day on the state of
her mind--her alternations of hope and fear;
the one founded on the boundlessness of the mercy of her heavenly Father,
and the other on her manifold transgressions of His law.
The beginning of the week after M. A. M. left her,
she seemed scarcely to dare to cherish the hope that such sins
as she had been guilty of would be blotted out;
and at seasons she was much depressed; but at others was enabled to hope.

On the 22nd, when E. C. visited her, she thought her much sunk.
After recognizing her, she laid for some time as in a stupor, then suddenly started up,
exclaiming, "`Oh how I long to be with Christ,
but I want an assurance that He will accept me.
I do not care how much or how long the poor body suffers,
so that I am made meet for an inheritance with the saints in glory.
Sometimes I feel, for a time, as if all would be well,
and then I am afraid I am deceiving myself--but yet, His mercy is boundless.`"
She then inquired, with earnestness,
if E. C. thought she might find mercy--begging her to pray,
that she might be more enlightened, and that she might be accepted.
She then herself supplicated, in much agitation and weakness, for mercy.
The next day, when +++_______+++ visited her, the clouds were removed from her sky,
and she appeared indeed to have known the dawning of a glorious, an eternal day.
She remarked on the rapidity with which she was sinking,
and said she had been much impressed with the idea of walking through the valley of
the "`shadow of death,`" inquiring when she thought she should have to walk in it.
She told her she believed she was already in it,
and she trusted she was not unsupported or alone.
"`Oh no,`" she said, "`my Saviour`'s arms are underneath.
I heard, as plainly as with my natural ear, last night, "`Thy sins are forgiven.`"
The sweet peace I have ever since enjoyed, convinces me I am not deceiving myself.
Oh the boundless mercy of my God!`"

The evening of that day--the greater part of which was spent in prayer and praise--
she desired all her dear absent friends might be informed that she died in faith,
and in the love of Christ.
She spoke of having seen the robe of righteousness
which was prepared for her--"`it was a spotless robe.`"
Her last words were, "`You must let me go, I cannot stay;`" and at half-past two,
on the morning of the 24th, she gently breathed her last!
Ought not her experience to encourage us, my beloved brother, to trust, and not be afraid?
I know of no one who appeared to have greater dread of death than she had,
yet it was made easy to her, by trusting in the arm of everlasting strength!
And to every Christian traveller, who daily strives to know and to do his Lord`'s will,
I do confidently believe, that this valley,
which our nature shrinks from passing through,
will be brightened by a Saviour`'s presence;
and he will be strengthened to pass undismayed, the portal which,
through redeeming mercy,
we trust will introduce him to a blessed inheritance in the heavenly Canaan!
Let me encourage thee, my dearest Charles to pursue thy way faithfully.
Oh do not be ashamed to confess Christ before men;
never yield to doing any thing thou believes to be contrary to His will,
however it may appear in the sight of thy companions, for doing so must be wrong,
and therefore cause thee, in after days,
deep suffering--but oh mayest thou be enabled to go onwards, daily, yea hourly,
looking to thy heavenly Guide.
To Him I most affectionately commend thee, and most hastily bid thee farewell.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Bristol, 10th 3mo. 1835.

My beloved Charles! how great is the importance
of our keeping constantly on the watch-tower.
How necessary is it for us constantly to bear in mind the language of the prophet,
"`In quietness and confidence shall be your strength.`"
I do, indeed, most earnestly and affectionately desire, that thou, my beloved brother,
mayest be enabled to go faithfully on thy way--that, by keeping close unto Jesus,
thou mayest experience His preserving power, and know Him to be, continually, thy refuge,
shield, and hiding-place!
I hope it will not be long before I again hear from thee,
and how should I rejoice to hear that the "`noise of
strife`" in our borders had subsided,
and that the precious badge of discipleship was more manifestly spread over all.
In the spirit of love alone should any subject of importance be entered into; and oh,
that it may prevail more and more in our hearts!

Next week our quarterly meeting is to be held here.
I trust it may prove a satisfactory one; but I grieve to see the desire,
I fear increasing, to watch the words of all, to find out,
not whether they belong to Christ, but on which side they are,
amongst the members of our part of the church militant.
Amidst the feelings of discouragement and depression,
caused by contemplating the state of things amongst us, it is consolatory and cheering,
at seasons, to look forward to the time when all the frailties,
of which we have now so many, shall be forever cast aside,
and bright and glorious shall be the Christian`'s rest!
Oh, if we are but permitted, at the close of time,
to know a transition from its trials to the realms of everlasting blessedness;
for the way, however painful, by which we have been led,
we shall know the song of thanksgiving to be put
into our mouths--to Him who hath redeemed us.
With dearest love, thy affectionately-attached sister.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
Leominster.

I was quite concerned my beloved mother, to find, that the cloud which covered my way,
increased the one which already shadowed thine.
I was not aware that I had said any thing calculated to produce such an effect;
and I sincerely trust that it has, ere this, passed away.
It would not be good for me, nor do I desire,
that clouds should never be spread over my path; but in the darkest of them,
I long for an increasing ability to trust in the love and mercy of my heavenly Guide;
and oh my beloved mother, may He enable thee to do so; and whilst suffering,
may we all be encouraged by the conviction,
that it is only for a short season we shall remain here,
and that we need such discipline to make us feel the entire
insufficiency of the things of time to afford solid comfort,
and the preciousness of "`the hope that maketh not ashamed.`"
May this hope be as an anchor to thy soul, my endeared parent,
whether thy bark be permitted to glide smoothly on the sea of life,
or whether it be tossed by the tempestuous billow.
Oh it is sweet to me to think, that all our afflictions are,
and can be but for a "`moment,`" and if in that moment they tend to
work out for us "`a far more exceeding and eternal weight of glory,`"
with what grateful adoration shall we retrace the past!
My dear parents, I do long, in any way in my power,
to brighten the remainder of your journey in the wilderness.
I do earnestly desire to be strengthened to smooth any of your rough paths; but,
in deeply feeling my entire inability,
I would crave for you the felt guidance of the Shepherd of Israel.
May He mercifully condescend to lead you, and each of your children,
to the fold of safety and of peace.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Leominster, 13th 1mo. 1835.

When enabled, even in a slight degree,
to contemplate the blessedness of the redeemed above,
I cannot but feel inexpressible gratitude that her^
footnote:[In allusion to the decease of a loved friend.]
tribulated path on earth has been exchanged, I doubt not,
for an inheritance in that land "`whose inhabitants shall not say I am sick,`" and
where she so very fervently longed to be allowed to enter--feeling so very deeply
those darts of the enemy to which we are still exposed,
and which, oh may we more constantly remember, we can none of us resist,
unless clothed with the "`whole armour of God.`"
Were it not for the knowledge that this armour is sufficient for all
who have enlisted themselves under the banner of the Prince of peace,
deep discouragement would often tend to sink the soul of the Christian warrior; but,
my beloved mother, let us remember,
that not only has the Captain of our salvation left us
an example that we should follow His steps,
but graciously and tenderly does He continue, in the day of battle,
to cover the heads of His little ones, and, as they yield their all to Him,
preserve them from the fear of evil.
Almost unconsciously have I turned from the blessed experience of my departed friend,
to those who are still exposed to the dangers of the wilderness.
Thou, my endeared parent, hast been made alive to many of these;
thou hast been permitted to feel the piercing
thorns which surround the way of the traveller:
and thou hast known a longing for a place of safety from all storms,
under the shadow of the "`Rock of Ages`"--and thy advancement in this knowledge,
I do very fervently desire; yea,
that thou mayest be enabled to build upon this foundation that
work which will endure the trying of the fire,
by which, the apostle assures us, every man`'s work shall be tried.

Many indeed are the cares which surround thee,
appearing particularly calculated to retard thy progress in the way everlasting; but,
my beloved mother, let me affectionately intreat thee, not to permit them to do so.
Looking continually for help from above--casting thy cares on Him who is able and
willing to bear them--mayest thou daily experience a renewal of strength,
and be favoured to know, from time to time,
the sufficiency of the help which is laid on one who is mighty!

[.letter-heading]
To Her Sister S+++______+++.

[.signed-section-context-open]
Leominster, 1mo. 1835.

Although the time of our separation will probably be very short, I do not,
my beloved S+++______+++, like to leave thee without expressing, in this way,
the earnest desires I feel that thou mayest be enabled
to go on thy way in satisfaction and in peace!
I am not surprised that thou shouldst contemplate much difficulty in pursuing a path,
which, until the last two weeks,
has been to thee an untrodden one--so much alone
as thou mayest feel where I have left thee--but,
my precious girl, let the knowledge of thy need, and utter helplessness,
lead thee continually to seek help of Him who is able and
willing to extend aid to the very feeblest of His flock,
if in sincerity they seek it of Him.
Never, my beloved S+++______+++,
enter upon thy daily duties without endeavouring to seek His guidance and protection,
and He who heareth the cry of the ravens, thou mayest rest assured, will,
as thou faithfully endeavours to follow Him,
manifest himself to be "`merciful and gracious, slow to anger, and of great kindness!`"
Oh how do I long that thou mayest be strengthened to walk before Him
in the manner which is alone acceptable in His sight;
and be thus enabled to lead thy precious charge, and to walk with them in safe paths.
In thy intercourse with them,
ever direct them to the attainment of useful and profitable knowledge;
in thy walks with them, try to make the time pass pleasantly, yet usefully away;
and whilst looking on the works of nature,
watch for every suitable opportunity of turning
their thoughts to Him who made all things,
and whom they have, I think,
been sweetly taught to acknowledge in the works of His hands!
I should like to have a very frequent and particular account of thy
future footsteps--thou knowest thou mayest confide in me,
and I do indeed desire to be enabled to feel for thy trials,
and as much as possible to smooth the way for thee.
But, dear, dear S+++______+++, remember, thou mayest, and I trust wilt,
have a never failing and ever present Helper;
and to His care do I at this time commend thee.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Coalbrookdale, 1mo. 1835.

I have been much interested in spending more time in
+++_______+++`'s company than I ever before did;
he has been very closely occupied during the whole of his stay,
in labouring for the best welfare of his friends whilst paying visits to them.
In the morning meeting yesterday, he was long and very powerfully engaged,
both in testimony and supplication.
He alluded to the "`baptism of suffering`" which he had been permitted to pass through,
from the belief, that through the unfaithfulness of many,
the cause of truth had not prospered as ought to have been the case.
He addressed those who had lingered on their way--those who had long been wanderers,
submitting to the iron yoke of Satan--and those who, in early life,
had felt the name of Christ to be precious,
but who had not wholly given themselves up to Him.
He also spoke encouraging language to those who might yet be called a living army.
And very earnestly did he endeavour to turn our
attention to the privileges of the righteous,
both here and hereafter,
by leading us to contemplate the taking away the
veil which separates us from the eternal scene,
to behold the fulness of the glory of those who have gone before us into heaven.
On another occasion he strikingly alluded to the state of things amongst us,
entreating us, whilst with godly jealousy we watch over the foundation, Christ Jesus,
never to mar or tamper with the beautiful superstructure.
He believed the spiritual views of our society were spreading amongst other Christians,
but it was not the time for us to lower our standard, etc. etc.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
Leominster, 6th 8mo. 1835.

The frequent prostration of thy strength is indeed, my dear mother, calculated,
in no common way, to remind thee of the frailty of the poor tabernacle;
whilst it must also, I think,
deeply impress thy heart with the necessity of "`pressing forwards towards
the mark of the prize of our high calling;`" "`laying aside every weight,
and the sin which doth so easily beset us.`"
But, amidst the many, many cares which surround, I have, of late,
been increasingly sensible,
that great are the difficulties in the way of leaving all to follow Christ; yet,
my beloved mother,
when we remember that His strength will be afforded for our many necessities,
if we seek it of Him,
we have cause for encouragement--we have abundant
reason to cast our burdens upon the Lord,
and to yield to Him the unreserved sacrifice of the whole heart.
My beloved, my much loved parent! let us ever remember that it must be a complete,
a full surrender.
We must not endeavour to hold the world in one hand and heaven in the other; but,
with full purpose of heart, "`inquire the way to Zion,
with our faces thitherward:`" and oh how blessed are they who are
enabled to do this--who can look on the every day trials of life as
nothing in comparison to the joy which will hereafter be revealed to
those who love the Lord Jesus Christ in sincerity!
Much do I desire that we may be strengthened to regard, in a proper light,
some of the difficulties which appear, at present, increasingly to lie in our way;
and whilst we gratefully recognize the hand of the bounteous Giver of all,
in the many unmerited blessings of our allotment,
be thankful also to Him for those circumstances which seem
peculiarly calculated to wean our hearts from things of earth,
and fix our hopes on heaven!
The trials which come immediately from our heavenly Father, are, however,
I can fully agree with thee in thinking,
much more easy to receive than those which come through our fellow creatures;
but for the effect of these I believe we are also answerable,
and how do I long that we may be strengthened
more and more to examine what this has been,
and is, on our minds.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Southfield, 20th 8mo. 1835.

I have not forgotten, my beloved mother,
that tomorrow will be the anniversary of thy birth;
and I am glad to avail myself of a little time before I leave my room,
for assuring thee that my thoughts will often be with thee,
and that I shall very affectionately and earnestly desire thy truest welfare.
I do most earnestly long, that spiritual blessings may attend thee;
that through simple obedience to the requirings of Israel`'s Shepherd,
thou mayest be fed by Him in a good pasture--led by the still waters of life.
And how highly privileged are the willing and obedient!
How blessed are the faithful disciples of a crucified Saviour!
In His strength-they feel that they are strong, and clothed with His armour,
they are not afraid to stand in the battle,
although they have to wrestle with very potent enemies--
"`we wrestle not against flesh and blood,
but against principalities,`" etc.
Thou, my much loved mother, hast, I believe,
often known this to be verified in thy experience;
and I would also hope that thou hast known, in some degree,
the power of the "`Captain of our salvation`"--the omnipotency of His
arm! but I long to see thee leaning more constantly upon it;
I long to see thee enabled to cast all thy cares on Him who
mercifully condescendeth still to care for His people;
then would hard things be made easy, and crooked things straight; and,
through His sustaining power, thou wouldst be enabled to rejoice in tribulation,
"`knowing that tribulation worketh patience, patience experience, and experience hope,
and hope maketh not ashamed, because the love of God is shed abroad in the heart.`"
I trust it is under a renewed sense of the extension of this love,
that my heart is filled this morning with desires for thee, my beloved mother;
that my spirit is bowed in fervent craving for thy advancement in the path of life;
for thy preservation from all the snares of the enemy, our unwearied adversary!

During the past year many have been the waves which have rolled over thee;
many the storms which have threatened to overwhelm.
Yet, my dear mother, canst thou not also speak of the still waters?
Art thou not also bound to acknowledge mercies--boundless mercies!
Then may the retrospect of the last twelve months, though it may deeply humble,
also encourage thee to enter into closer covenant with
that God who has hitherto cared for thee,
and to whom belong the issues from death;
and whether it is His will for thee long to remain in the wilderness,
or to shorten thy days, all would then be well!
And I confidently hope that all anxiety respecting the future may be spared thee,
by committing thyself to His care,
without whose knowledge a sparrow falleth not to the ground.

[.letter-heading]
To Her Brother Charles.

[.signed-section-context-open]
Leominster, 25th 12mo. 1835.

I trust, my beloved brother, thou hast not thought me ungrateful, for not, ere this,
replying to thy valued letter.
My little note from the Dale, would, I believe,
convince thee of my most affectionate remembrance; whilst it would also convey to thee,
an idea of the bitterness of the cup^
footnote:[In allusion to the decease of her loved friend S. D.]
it has pleased my heavenly Father to hand to me, and of its very dregs,
my dearest Charles, I have partaken largely--still, I must speak of mercy!
I must yet acknowledge the infinite mercy of the Lord!
Although severely "`chastened,`" I have not been killed; although deeply towed down,
I have not been destroyed! and, in my moments of severest suffering, I have been,
and am strengthened to believe, that this dispensation has been designed,
not only to prove me, but to bring me nearer to that Saviour, who I long, henceforward,
may become, increasingly, the "`object of my first desire`" yea, my "`all in all!`"
My beloved brother!
I have needed this severe stroke.

Do not, I entreat thee, murmur because the rod has been extended to thy too fondly loved,
but frail and unworthy sister; rather endeavour with her, to feel really thankful,
that she is counted worthy to suffer,
and rejoicingly remember that "`whom the Lord loveth he chasteneth.`"
And shall we shrink from the scourging with which He is
mercifully pleased to receive His children?
I am so fully convinced of his unfailing love, that I feel able at this moment,
to commit my all to Him, desiring only that He may be glorified!
Oh what does it signify, my much loved brother, if He but be with us,
whether we walk in an unclouded way, or through the deep, deep waters?
And can the fiery flames of the furnace, scorch those who are sustained,
when walking through it, with the presence of their beloved?
And since, though I must acknowledge that I have walked as through the fiery furnace,
I am also enabled to say, that I have not been there alone, surely, my beloved Charles,
I ought, with gratitude, to retrace the past,
and with humble confidence contemplate the future.
Yes, the consolations of the gospel are sufficient to convey comfort to the soul,
even in moments of the greatest extremity; help is afforded to the followers of the Lamb,
under the most afflicting dispensations; for one of the least of these,
my beloved brother, has, in her deepest suffering,
been at seasons comforted by the "`Comforter of spirits!`"
And though still bowed down,
there are moments when the song of praise is put into
my heart on behalf of that tenderly loved one,
who has been gathered, I cannot doubt, into the fold of everlasting rest!
Her memory will be to me very precious;
and I long that the undoubted conviction of her eternal safety,
may prove a daily incitement to me, to stand with my loins girt about,
and my lamp burning,
ready to obey the summons of my Lord--whether that summons be to put off mortality,
or to go forwards on the field of battle!

From my dear aunt thou wouldst doubtless hear,
that my precious friend did not appear aware
that she was about to enter the eternal world.
I have been preserved from doubting, that in best wisdom it was hid from her eyes.
Whilst proving to others, by her walk of humble dedication, that she was the Lord`'s,
she had gone sorrowing on her way; and oh,
how bright! how indescribably glorious! must have been the "`fulness of joy`" on which,
through redeeming mercy, I most confidingly believe, she entered,
when the veil was withdrawn which separates us from the unseen world,
and she had passed the stream.--When we meet,
should we be permitted to do so in a few weeks,
I shall like to converse with thee of this tenderly loved one,
to whom my heart was bound by the strongest ties--ties which
were not loosened till she was called to her heavenly home.
The wilderness in which I yet sojourn, she has safely passed through,
and I must hasten forwards!
I rejoice in believing that this is not my rest.

My much loved brother!
I trust thou art enabled to go faithfully on thy way;
and let not the falling of others discourage thee! let us look upwards,
and look forwards--perhaps our journey may not be long; oh that we may, at the end of it,
be permitted to enter on that rest which we believe to
be the blessed portion of my precious friend.

[.letter-heading]
To Her Parents.

[.signed-section-context-open]
Leominster, 5mo. 1836.

My beloved parents, be not too much cast down at the heaving of the stormy billows.
In a short time, "`a little moment,`" all these trials will have passed away, and,
if the effect designed by all our afflictions be mercifully accomplished,
we shall have cause to rejoice, and give thanks for them!
When I began writing, my heart was very, very heavy; now I feel animated by the belief,
the sweetly supporting belief, that, bitter as our present trial is,
it will be of use to some of us,
even if it tend only to lead us to watch more constantly "`over one another in love.`"

[.letter-heading]
To Her Sister S+++______+++.

[.signed-section-context-open]
5mo. 1836.

In close attention to the work of thy own soul`'s salvation,
and in watching the best interests of those most dear to thee,
I believe thou wilt find that there is no time for controversy;
and although thou mayest sometimes have to hear it,
I hope thou wilt be preserved from entering into
any conversation calculated to disturb the mind,
instead of preparing it for devotion; and do not, my dear S.,
allow what may be said in meeting to be afterwards the subject of discourse,
but try to learn from it some useful lesson, whatever it may be.
In the present state of our society, and of the world at large,
I am most deeply sensible of the great importance of
dependance on the "`Minister of ministers`" alone--and of Him,
I humbly hope, thou wilt be instructed, led, strengthened!

Impress continually on the precious little ones the truth,
that not the language of the lips alone, but of the heart,
is acceptable to our heavenly Father.
Oh seek of Him ability to train them to His glory!
What shall I say more my beloved S+++______+++? Look upwards, and look forwards!
May thy loins "`be girded about,
and thy light burning;`" and mayest thou thus be found waiting
the arrival of thy Lord--that whether He come in the morning,
noon, or evening of thy day, thou mayest be found ready.

[.letter-heading]
To the Same.

[.signed-section-context-open]
26th 6mo. 1836.

Yes, my beloved girl,
twenty-three years have fled since I first entered this changing
scene--twenty-three years of invaluable time are gone forever!
It is a solemn, a deeply interesting thought; and yet,
whilst my many sins of omission and of commission do, at times, oppress my spirit,
there are moments when, in the felt power of the Saviour of sinners, I can, I do,
rejoice in believing, that having fled to Him for refuge,
as I am--enabled constantly to look to Him--I may mark
with joy the rapidity with which time passes away,
from the humble hope, that when all my days on earth are over, I may,
through redeeming and unbounded mercy, forever rest in Jesus!
This most precious hope is truly animating, yet I am not now anxious to depart;
and I trust I shall be increasingly enabled to adopt the apostle`'s language,
"`to live is Christ;`" and to crave that guidance without which,
I must continually go astray.

[.letter-heading]
To the Same.

[.signed-section-context-open]
1836.

Oh do not shrink, my beloved girl, from acknowledging Him in thy daily walk,
whom thou desires should be thy "`all in all;`" and to Him alone I would direct thee,
as an all-sufficient Counsellor.
If thy heart is heavy, go to Jesus!
If it is filled with desire after heavenly good, go to Jesus!
If it is tried with the infirmities of others, go to Jesus!
If thou art oppressed with earthly cares, go cast them all at the feet of Jesus!
Yes, my loved girl, seek an abiding there, and thou wilt be strengthened,
daily and hourly, to walk as He would have thee to walk, in the path of simple obedience.

I thought thou wouldest much enjoy dear +++_______+++`'s society.
Didst thou suppose I was ready to judge her?
From the question thou asked, I should almost suppose thou didst; but, believe me,
my beloved girl,
such has not been the case--too much do I find
to look after in the vineyard of my own heart,
to watch for the weeds in those of others; although when they do appear,
I should desire not to shrink, improperly?
from acting as I would wish others should act towards me in similar circumstances.

I must again entreat thee to be faithful--again encourage thee to look forwards,
and not backwards in the heavenly race!
My much loved S+++______+++, remember to what thou art called, and be not ashamed of Him who,
in the last solemn hour, is alone sufficient to uphold the departing spirit.`"

[.letter-heading]
To Her Sister J+++______+++.

[.signed-section-context-open]
Leominster, 1mo. 1836.

Thy mention of +++_______+++ interested me.
In the prospect of becoming a clergyman`'s wife, she must, I should think,
have much to pass through, not only in leaving our society,
to the principles of which I thought she had been sincerely attached,
but in the great responsibility of her future allotment.
Under whatever name, they who are united to those who watch over the flock,
appear to me particularly called on to walk in the "`newness of life;`" and
to those who are faithfully endeavouring to do so,
how wide a field of usefulness is presented!

The principles professed by our society are, however, too precious to me,
to allow of my hearing of any adopting others, without regret.
I long most earnestly,
for the work of righteousness to spread in the earth--for more
faithful labourers to be raised in all parts of the harvest!
Truly this is indeed great, and, individually, we surely have much to answer for.
We have each of us, I believe, much influence on many,
and how important does it appear that this should be a right one.
I trust, my beloved sister, thou hast been, since thy return home,
permitted to derive strength and refreshment from daily retirement; but if,
whilst seeking to be fed, thou hast not felt the sustaining thou desired,
oh do not be discouraged,
my much loved sister--"`the husbandman waiteth for the precious fruit of the earth,
and hath long patience for it, until he receiveth the early and the latter rain.`"
We must be also patient, but if we faint not, rest assured, dearest J+++______+++,
"`we shall reap,`" if we are strengthened to persevere in well doing.`"

[.letter-heading]
To Her Brother Charles.

[.signed-section-context-open]
Leominster, 28th 10mo. 1836.

Thy allusion to travelling,
reminded me of J. Newton`'s view of a Christian situated in
London--he compared such to being "`amidst the flames.`"
Yet, dearest Charles, amidst the flames there is a power, thou knowest,
that can preserve--thou knowest it is sufficient to bring out, not only unscorched,
but purified.
That such may be thy blessed experience, I earnestly and affectionately desire.

[.letter-heading]
To the Same.

Thou needest not, my beloved Charles, be at all afraid of my entering into discussion.
I am so fully convinced that it is not calculated, in any way,
to help the traveller in his journey heavenward,
that I much trust that I may ever be preserved from doing so.
So weak, so frail do I feel myself to be, that it would, I believe,
prove a great stumbling-block in my way,
if I gave way to a spirit of controversy--that spirit
which is indeed painfully calculated to divide in Jacob,
and to scatter in Israel.

The instances thou mentions, as lately placed before thee, of the uncertainty of life,
are indeed striking; and I trust would convey a lesson to many amongst you.
How very great is the individual work, to the consideration of which,
these things should lead us!
Surely, surely, we have no time for controversy;
but should each be seeking to possess for ourselves,
a well grounded hope of a glorious immortality.

[.letter-heading]
To Her Sister Elizabeth.

And now, dear Elizabeth, a few questions,
in allusion to the subject of most importance to us.
Are the things of time appearing of less value in thy sight;
and art thou earnestly and steadily striving to attend to those of eternity?
Each hour seeking ability to do what thou knowest to be thy heavenly Father`'s will?
Dost thou endeavour to improve the time thou passes with those younger than thyself,
for whom thou art so much interested?
Dost thou feel greater patience with thy young charge at home,
when they are not quite so obedient as thou couldst desire?
Dost thou in attending to them, desire ever to keep in view their best interests?
I long, my much loved Elizabeth, to know that thou art making progress in the narrow way,
and that in every difficulty thou finds therein,
thou mayest be enabled to look unto Jesus, and thus be strengthened to overcome it.
I hope dear S+++______+++ and thee learn scripture together, and repeat it to each other.

[.letter-heading]
To the Same.

[.signed-section-context-open]
10mo. 1836.

I generally visit the poor children two or three times in the week,
as well as some other poor people, for whom I am interested.
Our young scholars are proceeding quite satisfactorily with their learning,
and manifest an interest in the reading of the scriptures which is very striking,
and I often think should be instructive.
I should like thee to see these poor cottagers; thou wouldst, I know,
be pleased with them.

It is most sweet to think of the hour when separation
will be no more known from any of our loved ones,
when nothing will interrupt the brightness of our joys;
but for this blessed period we must seek on earth a preparation.
How could we prize the privileges of the heavenly world,
whilst our hearts are cleaving to the dust?
No. We must seek to know the "`washing of regeneration`" before we
can hope for entrance into the "`city of God`"--we must be born again.
Mayest thou and may I, my much loved girl,
seek ability more constantly to bring forth the precious fruits of the Spirit.

[.letter-heading]
To the Same.

Thy journal note was very acceptable, and thy warm affection is very sweet to me.
I long that we may be, all of us,
more and more closely bound by the precious ties of heavenly love; but, remember,
my beloved girl, this love, when fully shed abroad in the heart,
not only tends to exclude every unkind action, but the unkind word, the unkind thought;
and do be very careful not to cherish any improper feelings
towards any one--remember the example left us by our Saviour,
m His conduct to His bitterest enemies.

[.letter-heading]
To the Same.

I have just gained permission to write to thee, my dearest Elizabeth, and I am glad,
although with a trembling hand, to avail myself of it.
It is with peculiar feelings of interest I watch the approach of thy coming birthday,
because I believe thou mayest feel encouraged to
press forwards in the "`straight and narrow way.`

The angel of affliction has visited thee,
and I trust has conveyed a lesson of instruction never to be forgotten.
This is not our rest.
Oh that these words may be deeply engraven on thy heart--and
let not the "`world`'s dread laugh,`" ever tempt,
or, rather, lead thee from the path of duty!
My precious Elizabeth! press forwards--seek ability to yield the fruits of righteousness;
then mayest thou know, assuredly, that the work of grace is begun in thy soul.
I must not write more now.

Farewell, my beloved child.
I am, as ever, thine, most affectionately.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
Leominster, 12m. 1836.

My dearest mother! the time is short!
The knowledge of its being so, and the rapidity with which it flies away,
sometimes casts a gleam of brightness over my way, even when it has been dark and dreary.
It does at this moment do so; whilst the fervent desire arises in my heart,
that we may all seek increasingly,
to be found as servants waiting the coming of their Lord--our loins girded about,
and our lamps burning!
Another week is nearly come to a close,
and before the time arrives for me to seek repose,
I must lay aside my pen to have a little quietness, for "`talking with my past hours.`"
It is cheering to think, that many dear to me, and amongst them thyself, my dear mother,
may be engaged in a similar manner.
Surely, self-examination is a duty incumbent upon us all.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Leominster, 4th 1mo. 1837.

More critical symptoms in thy complaint are, indeed,
likely to lead to very solemn considerations; yet, my dearest mother,
whilst this is the case--whilst thou art led more earnestly to crave
ability to bring forth the precious "`fruits of the Spirit,`" and day
by day to lean more entirely upon the arm of power--I trust the
contemplation of the future will not bow thee down.
To be brought low under a deep conviction of our very great unworthiness, is, I believe,
a privilege we should all seek after, for it is in the felt weakness of the creature,
that the power of the Saviour is most manifestly made
known--there it is that His strength is perfected!

Unspeakably sweet is it to believe, also, that His mercy is infinite,
and that His lovingkindness fails not.
Yet, whilst I deeply feel this, far be it from me, to lull into false security,
any immortal spirit, and especially those for whom, I believe I may truly say,
my soul has been bowed from time to time,
in fervent prayer to the Father of mercies--far be it from me, my endeared parent,
even to cry to thee, "`Peace, peace, when there is no peace.`"
No!
I would not help to raise a barrier which must be broken down ere an
admission can be administered to any into the land of light;
but I would intreat thee to trust in the faithfulness of a "`covenant
keeping God,`" and wholly and unreservedly give thyself unto Him.
The retrospect of the past, I doubt not,
is often clouded by the recollection of many sins of omission and commission.
"`The unpaid vow, the broken covenant, the failed resolution.`"
After using these words, R. B. intreated us to bring these unto Jesus;
and it is in doing this, and in casting all thy care upon Him,
that I believe thou wilt find sweetly refreshing rest unto thy soul,
and be enabled to trust thy all in His hands.
Oh do not be discouraged if darkness may, again and again, cover thy way,
unbroken by the beams of light from above.
Do not, oh do not, cast away thy confidence,
for I do assuredly believe that all things will work together for thy good,
and that thou wilt be made meet for that inheritance which is "`incorruptible, undefiled,
and that fadeth not away, reserved in heaven for those who are kept by the power of God,
through faith, unto salvation!`"

I feel most tenderly for thy bodily sufferings, whilst I humbly trust,
thou art enabled to trace in them the hand of mercy,
affording one precious proof of the remembrance of a compassionate Father, who,
knowing exactly the portion needed for His children,
will make it what He knows is best for them, and enable them, if they seek help from Him,
to accept it with resignation and thankfulness.

[.letter-heading]
To the Same.

+++[+++When in very poor health,
in allusion to an affliction unconnected with her bodily state, Mary Ann writes:]

[.small-break]
'''

That I needed such a trial, I unhesitatingly believe; and while most deeply feeling it,
the chief desire of my heart has been, and is, that it may be sweetly sanctified.
I trust it has in some degree been thus;
yet I have daily proof of my need of deeper humiliation,
and an increased and abiding sense of my very great unworthiness.
Oh my beloved mother, thou knowest not how much, how very much,
I need to keep me at the footstool of divine mercy;
and by whatever means I may be kept there, I trust those means may be resorted to,
even should the suffering caused by them be comparable to the refiner`'s fire.
But whilst I write this, I feel that I should be struck with a sense of my deep frailty,
for I do not live as if this were the desire of my heart.

[.letter-heading]
To the Same.

It is seventh day evening--one, thou knowest, my beloved mother,
which is marked by more than usual interest to me, as preceding the day of outward rest.
A sweet stillness reigns around me,
and in it my thoughts have turned towards thee with so much affection,
that I am induced thus to endeavour, for a short time, to converse with thee.
I fear, from thy allusion to thy mental state,
that thou continues to be too much bowed down with discouragement.
Oh why, my dear mother, is this the case?
Thou dost not doubt the power and willingness of the Saviour to deliver,
and though thou mayest, at moments, be ready to acknowledge very many transgressions,
will He not be glorified in saving from the power of the destroyer,
either of His little ones--the very least of His flock?
Oh that thou mayest be strengthened to cast all thy care upon Him!

It is very kind to enter into my mingled feelings in the
renewed prospect of a longer tarriance in the wilderness;
that they should have been mingled, has, afresh, tended to convince me of my frailty,
for does it not prove, that my will was not entirely conformed to the divine will?

Farewell, my very dear parent; ere thou receives this,
I expect another sheet will have reached thee from Aberystwith,
but I thought I should like here to record the present feeling of my heart.

[.letter-heading]
To Her Sister S+++______+++.

[.signed-section-context-open]
11th 5mo. 1837.

No words can I find to describe my anxious solicitude for thee,
that thou mayest "`go forwards,`" that nothing may prevent thy
yielding up the sacrifice of a devoted heart,
that each day thou mayest seek ability to live to the "`glory of God;`" each
hour seek of Him help to perform what He requires of thy hands;
and as thou art seeking to be found at the "`feet of Jesus,`"
as thou art striving there to obtain a knowledge of His will,
thy hands will, I trust, be strengthened in Him,
and thou wilt be enabled to perform thy duties
to thy satisfaction and peace--and this peace,
I may assure thee from experience,
is far superior to any which the even well
obtained commendation of our friends can bestow.
If thou art favoured to enjoy the "`light of His
countenance`" who is indeed strength in weakness,
thou wilt, I believe, be prepared to acknowledge, from season to season,
the frailty of every arm of flesh, and the omnipotency of that arm of power,
which alone is "`able to deliver;`" trust in it fully, lean upon it confidingly,
my beloved girl, and thou needest not fear the "`whirlwind and the storm,
or the rising billows; remember thy refuge--fly to it, and seek rest there.`"

[.letter-heading]
To Her Brother Charles.

[.signed-section-context-open]
Leominster, 6th 6mo. 1837.

In the prospect of parting from thee, my beloved brother,
the watchword arising in my heart for thee is, to "`keep thyself from idols.`"
I cannot tell thee with what indescribably painful feelings I observe the manner,
in which thou regards thy poor frail sister;
oh that I could impress upon thy heart a right
sense of her weakness and inability to help thee,
as she would desire, in the heavenly way.
Whilst, I trust, we may know increasing union of spirit, I must, dearest Charles,
intreat thee to look from her to the Shepherd of Israel for help,
and to depend wholly for guidance upon Him!
Be more steadfast, my dear brother,
in His service! more constantly seek the knowledge of His will,
and ability to perform it!
Oh I would that thou shouldst be "`complete in
Christ,`" that "`He may be thy all in all.`"
I must intreat thee, my beloved brother,
to crave ability to commit me unreservedly to the care of Him,
who has so mercifully cared for me all the days of my life, and who, I can still believe,
will help me to my journey`'s end.
Accept very much love from thy affectionate sister.

[.letter-heading]
To Her Parents.

[.signed-section-context-open]
Leominster, 15th 6mo. 1837.

I am, I think, really gaining strength.
Thus, my endeared parents, it again seems probable,
that I may be restored to my former health,
after another season in which the future has been marked with great uncertainty.
You will not be surprised that very mingled feelings should mark my late indisposition.
The power of the tempter has at moments appeared so overwhelming,
I mean the fear of yielding to it,
that I have felt it very difficult to realize a return
to the busy scenes of life with entire resignation.
My heart has sometimes almost sunk within me,
with the fear of wandering again from Him who
has so abundantly and tenderly cared for me.
I have not sufficiently remembered "`His strength to
succour and His will to save`"--Oh for a stronger faith.

Now it seems safest, indeed, the only safe way for me, (and alas,
that I have been so long in learning the lesson) to live one day at a time.

[.letter-heading]
To Her Mother.

[.signed-section-context-open]
Aberystwith, 14th 1mo. 1837.

I hope, my beloved mother, the appearance of a letter before the time I mentioned,
will not alarm you.
We thought you might be feeling anxious to know the effect of the travelling on me.
I think I have borne the journey much better than we could have at all anticipated;
but my cough is not yet much relieved.
Yet, my dear parents, I trust you will not feel this to be cause of much anxiety.
I feel quite ready to resort to any remedy my kind friend, G. D. F.,
thinks likely to be beneficial;
I feel sure he will kindly enter into the particulars of my case,
and it is far more satisfactory to me that he
should do so than any other person at a distance.
Do not, however, imagine that from desiring this,
I am at all anxious even for present increased ability for exertion:
there are moments when, on account of others,
it would be great comfort to be able to do more;
but I feel it an unspeakable favour that I am preserved from anxiety on this account,
and I am sometimes strengthened to think only of the passing moments.
May I ask you, my beloved parents,
not too earnestly to desire the restoration of my health.
I sometimes fear I am held too tightly by my tenderly loved and much interested friends.
Oh desire for me the spirit of entire resignation,
that whether I live or die I may be wholly the Lord`'s.

[.letter-heading]
To the Same.

Yes, my beloved mother,
I am spared to welcome in another of thy birthdays! and I can do it,
I rejoice to say--though not with unmingled feelings--
with those of humble thankfulness and confidence.
The deep, deep proving I have lately known,
has prepared me more and more to sympathize in the trials of others;
and in the prospect of a lengthened tarriance here, now opening before me,
one of the brightest gleams of light resting on my path,
is produced by the precious hope,
that I may be strengthened to bear the burdens of some inexpressibly dear to me,
and thus "`fulfill the law of Christ!`"
I feel as though I could thankfully rejoice to be permitted to spread flowers on,
or even to remove thorns from, the paths of my many loved ones.
But as I write, I am renewedly made sensible of my own unworthiness, and I deeply feel,
that of myself I am entirely unable to lend the
helping hand to any of my fellow travellers,
and that the blessing of preservation is the one I must most ardently crave,
in looking forwards to a lengthened tarriance here.
Ask this for me, my beloved mother, when thou art enabled to seek it for thyself.
In reviewing the past year,
I cannot but vividly remember the greatly increased bodily suffering which has marked it;
but I do rejoice in believing that tribulation has, in thy experience, worked patience,
and that, thy spirit will eventually rejoice in that "`hope, which maketh not ashamed,
because the love of God is shed abroad in the heart!`"

Be not, my dear mother,
too much discouraged if the clouds are still dark which shadow thy way,
but in marking the gleams of mercy which appear in them, may thy soul be refreshed,
even when the suffering of the body may be very great.
This "`light affliction`" is, I believe, mercifully designed to,
and I humbly and confidently believe will,
work out for thee a "`far more exceeding and eternal weight of
glory,`" whilst thou looks not at the things which are seen.
Deeply do I sympathize in thy sufferings, my dear mother;
but with this precious hope I feel comforted.

That thou mayest more and more realize the presence,
the supporting presence of Israel`'s Shepherd,
is the earnest desire of thy very affectionate daughter.

[.letter-heading]
To Her Brother Charles.

[.signed-section-context-open]
Hotwells, 29th 3mo. 1838.

Once more, dearest Charles, although with a trembling hand,
I am engaged in writing to thee for thy birthday.
All that a sister can desire of good for thee, I believe I do on the present occasion;
and perhaps my desires are the more fervent from believing,
that this is the last on which I can address thee in this manner.
Yes, my much loved brother! _the last!_ for long ere the return of another, my warfare will
(we cannot but believe) be accomplished; and through "`mercy infinite,`" I humbly trust,
I shall have become one of the "`blest inhabitants of Zion!`"
And thou, I trust, wilt feel another inducement to press forwards in the heavenly race.
Oh how do I long that thou mayest do so;
and that thou mayest be the guide and counsellor of our younger brothers.
Dear Henry! my heart has often been filled with desires on his account--
oh tell him that I trust he will give up his heart to the Lord!
I must not, I believe, add more.
Accept my dearest love, and give it to dear Henry.

[.signed-section-closing]
Thine most affectionately,

[.signed-section-signature]
Mary Ann Gilpin.
